### ISSUE TITLE
Model weights and build files for MiniCPM-V

### ISSUE THREAD

**Issue by NSTiwari** [icecoins/mlc-MiniCPM#4]
Hi @icecoins,

I've been trying to follow the steps to setup the environment and compile the MiniCPM-V model. 
![image](https://github.com/icecoins/mlc-MiniCPM/assets/37960279/b5f16790-44a2-4968-87eb-809f999a8db4)

![image](https://github.com/icecoins/mlc-MiniCPM/assets/37960279/5ce7efe4-c3e0-43e0-a705-1ee7a81c0630)

However, I'm facing issues and am unable to proceed further. It would be really great of you if you can share the Android.tar file and the JAR build files.

**Comment by icecoins** [comment]
Hi, 
I know there're many bugs in MiniCPM's building, I tried to pr, but the owner of the git project rejected it.

I'm willing to share the relevant files.
Please let me know how to share files with you (email etc.)

And I would like to send the android studio project of this fork to you directly, as a zip file (1.22GB), together with MiniCPM-android.tar and MiniCPM-V-android.tar

If you want other files, please specify them with full file name.

**Comment by NSTiwari** [comment]
Hi, thank you for the response.
Yes, can you please share the complete Android Studio project along with the `MiniCPM-V-android.tar`, `MiniCPM-android.tar` files, as well as the .JAR files created under the build folder?  Email: tiwarinitin1999@gmail.com

Their name should look like the following files:
![image](https://github.com/icecoins/mlc-MiniCPM/assets/37960279/fa0f4565-ffd9-404b-919a-7bba6a798675)

**Comment by icecoins** [comment]
OK, I'll compress all files you need and send them via email, please check it later.
